jobs:
  include:
    - stage: test
      name: "Server test"
      language: csharp
      mono: none
      dist: xenial
      dotnet: 2.2
      solution: Invoro.Api.sln
      before_install: cd Invoro.Api
      sudo: required
      script:
          - dotnet restore Invoro.Api.sln
          - dotnet build Invoro.Api.sln
          - dotnet test Invoro.Api.sln
    - stage: test
      name: "web app test"
      language: node_js
      node_js:
        - "10"
      before_install: cd Invoro.WebApp/Invoro/invoro

    - stage: deploy
      name: "Docker Deploy as integration"
      if: tag IS NOT present
      dist: xenial
      language: generic
      before_script: cd Invoro.Api
      script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t invoro-api-stagging -f ./Invoro.Api/Dockerfile .
          - docker images
          - docker tag invoro-api-stagging $DOCKER_USERNAME/invoro-api-stagging
          - docker push $DOCKER_USERNAME/invoro-api-stagging
    - stage: deploy
      name: "Docker Deploy to as production"
      if: tag IS present 
      dist: xenial
      language: generic
      before_script: cd Invoro.Api
      script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t invoro-api -f ./Invoro.Api/Dockerfile .
          - docker images
          - docker tag invoro-api $DOCKER_USERNAME/invoro-api:$TRAVIS_TAG
          - docker push $DOCKER_USERNAME/invoro-api:$TRAVIS_TAG
    - stage: deploy
      name: "Publish to npm"
      language: generic
      node_js: "10"
      before_script: cd Invoro.WebApp/Invoro/invoro
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_AUTH_TOKEN"
        on:
          tags: true
          
#Only pull request      
branches:
  except:
  - master
  
notifications:
  email:
    recipients:
      - miz.yogev@gmail.com
      - levlevin90@gmail.com
    on_success: change
    on_failure: always